version: 2
updates:
  - package-ecosystem: uv
    directory: "/"
    schedule:
      interval: daily
      time: "07:00"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "07:00"
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/thirdparty/WCAG"
    schedule:
      interval: daily
      time: "07:00"
    open-pull-requests-limit: 10
