FROM debian:buster

RUN apt-get update \
    && apt-get install -y fontconfig libjpeg62-turbo libx11-6 libxcb1 libxext6 libxrender1 xfonts-75dpi xfonts-base wget

RUN wget --quiet https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.buster_arm64.deb \
    && dpkg -i wkhtmltox_0.12.6-1.buster_arm64.deb \
    && rm -f wkhtmltox_0.12.6-1.buster_arm64.deb

ADD ./Fonts/muli /usr/share/fonts/truetype/muli
RUN fc-cache -fv

ENTRYPOINT ["/bin/bash"]
