---
name: Test and quality

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          version: "0.11.23"
      - name: Install dependencies, run unit tests and check quality
        run: |
          npm install --ignore-scripts
          uv venv
          uv sync
          ci/unittest.sh
          ci/quality.sh
